### ISSUE TITLE
can't support UTF-8 ISO/IEC 10646-1 

### ISSUE THREAD

**Issue by CooperCao** [EricBerendsen/dvbinspector#11]
onid | tsid | sid | service_name | service_type | service_type description | service_provider_name | EIT_schedule_flag | EIT_present_following_flag | running_status | free_CA_mode
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 47 | �森購�1� | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 49 | 壹����� | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 50 | 年代��� | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 51 | �森��� | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 76 | WakuWaku Japan | 1 | digital television service |   | 1 | 1 | 4 | 0

original_network_id: 0x1 (1) => Société Européenne des Satellites
+-transport_stream_id: 0x1 (1)
  +-service (�森購�1�) [0]
  | +-service_id: 0x2F (47)
  | +-reserved_future_use: 0x3F (63)
  | +-EIT_schedule_flag: 0x1 (1) => EIT schedule information present in TS
  | +-EIT_present_following_flag: 0x1 (1) => EIT_present_following information present in TS
  | +-running_status: 0x4 (4) => running
  | +-free_CA_mode: 0x0 (0) => clear
  | +-service_descriptors_length: 0x16 (22)
  | +-Descriptor: service_descriptor [0]: 0x48 (72)
  |   +-service_type: 0x1 (1) => digital television service
  |   +-service_provider_name_encoding: -
  |   +-service_provider_name_length: 0x0 (0)
  |   +-service_provider_name: 
  |   +-service_name_encoding: UTF-8 encoding of ISO/IEC 10646-1
  |   +-service_name_length: 0x11 (17)
  |   +-service_name: �森購�1�
  +-service (壹�����) [1]
  | +-service_id: 0x31 (49)
  | +-reserved_future_use: 0x3F (63)
  | +-EIT_schedule_flag: 0x1 (1) => EIT schedule information present in TS
  | +-EIT_present_following_flag: 0x1 (1) => EIT_present_following information present in TS
  | +-running_status: 0x4 (4) => running
  | +-free_CA_mode: 0x0 (0) => clear
  | +-service_descriptors_length: 0x18 (24)
  | +-Descriptor: service_descriptor [0]: 0x48 (72)
  |   +-service_type: 0x1 (1) => digital television service
  |   +-service_provider_name_encoding: -
  |   +-service_provider_name_length: 0x0 (0)
  |   +-service_provider_name: 
  |   +-service_name_encoding: UTF-8 encoding of ISO/IEC 10646-1
  |   +-service_name_length: 0x13 (19)
  |   +-service_name: 壹�����
  +-service (年代���) [2]
  | +-service_id: 0x32 (50)
  | +-reserved_future_use: 0x3F (63)
  | +-EIT_schedule_flag: 0x1 (1) => EIT schedule information present in TS
  | +-EIT_present_following_flag: 0x1 (1) => EIT_present_following information present in TS
  | +-running_status: 0x4 (4) => running
  | +-free_CA_mode: 0x0 (0) => clear
  | +-service_descriptors_length: 0x15 (21)
  | +-Descriptor: service_descriptor [0]: 0x48 (72)
  |   +-service_type: 0x1 (1) => digital television service
  |   +-service_provider_name_encoding: -
  |   +-service_provider_name_length: 0x0 (0)
  |   +-service_provider_name: 
  |   +-service_name_encoding: UTF-8 encoding of ISO/IEC 10646-1
  |   +-service_name_length: 0x10 (16)
  |   +-service_name: 年代���
  +-service (�森���) [3]
  | +-service_id: 0x33 (51)
  | +-reserved_future_use: 0x3F (63)
  | +-EIT_schedule_flag: 0x1 (1) => EIT schedule information present in TS
  | +-EIT_present_following_flag: 0x1 (1) => EIT_present_following information present in TS
  | +-running_status: 0x4 (4) => running
  | +-free_CA_mode: 0x0 (0) => clear
  | +-service_descriptors_length: 0x15 (21)
  | +-Descriptor: service_descriptor [0]: 0x48 (72)
  |   +-service_type: 0x1 (1) => digital television service
  |   +-service_provider_name_encoding: -
  |   +-service_provider_name_length: 0x0 (0)
  |   +-service_provider_name: 
  |   +-service_name_encoding: UTF-8 encoding of ISO/IEC 10646-1
  |   +-service_name_length: 0x10 (16)
  |   +-service_name: �森���
  +-service (WakuWaku Japan) [4]
    +-service_id: 0x4C (76)
    +-reserved_future_use: 0x3F (63)
    +-EIT_schedule_flag: 0x1 (1) => EIT schedule information present in TS
    +-EIT_present_following_flag: 0x1 (1) => EIT_present_following information present in TS
    +-running_status: 0x4 (4) => running
    +-free_CA_mode: 0x0 (0) => clear
    +-service_descriptors_length: 0x14 (20)
    +-Descriptor: service_descriptor [0]: 0x48 (72)
      +-service_type: 0x1 (1) => digital television service
      +-service_provider_name_encoding: -
      +-service_provider_name_length: 0x0 (0)
      +-service_provider_name: 
      +-service_name_encoding: UTF-8 encoding of ISO/IEC 10646-1
      +-service_name_length: 0xF (15)
      +-service_name: WakuWaku Japan

SDT private_data:
private_data: 0x0001FF002FFF8016481401001115E69DB1E6A3AEE8B3BCE789A931E58FB00031FF8018481601001315E5A3B9E99BBBE8A696E696B0E8819EE58FB00032FF8015481301001015E5B9B4E4BBA3E696B0E8819EE58FB00033FF8015481301001015E69DB1E6 "..../...H.................1....1...H........................2...H.....................3...H........."

**Comment by EricBerendsen** [comment]
Thank you for reporting this. I have some questions;

- Can you provide me with a sample .ts file file? Use google drive, wetransfer, whatever you prefer.
- Are the service names displayed wrong all over the application, or 'only' when copying from the tree and table view?
- Can you provide examples what the real services names should look like?

**Comment by CooperCao** [comment]
[sample ts](https://drive.google.com/file/d/1Sa9eoPGwTtnDldBPetc0dihlLGvf1zpK/view?usp=sharing)
- I think the issue from this code :
``` 
public static String getString(final byte[] b, final int off, final int len) {
		int length = len;
		int offset = off;
		if(length<=0){
			return "";
		}
		final Charset charset = getCharSet(b, offset, length);
		final int charSetLen = getCharSetLen(b, offset);

		length -= charSetLen;
		offset += charSetLen;

		final byte[] filteredBytes = new byte[length];  // length is enough, might need less
		int filteredLength=0;

		// this is where we loose formatting, like newlines and character emphasis
		for (int i = offset; i < (offset + length); i++) {
			final byte c = b[i];
			if ((c > -97) && // bytes are signed, what we really mean is (b[i]<0x80)||(b[i]>0x9f)
					(c != 0)) { 
				filteredBytes[filteredLength++] = c;
			}
		}

		if(charset==null){
			return Iso6937ToUnicode.convert(filteredBytes, 0, filteredLength); //default for DVB
		}else{
			return new String(filteredBytes, 0, filteredLength,charset);
		}
	}
```
change to :
```
for (int i = offset; i < (offset + length); i++) {
            final byte c = data[i];
            // bytes are signed, what we really mean is (b[i]<0x80)||(b[i]>0x9f)
            if ((c > -97) && (c != 0)) {
                filteredBytes[filteredLength++] = c;
            } else if (data[off] == 0x11 || data[off] == 0x15) {
                // ISO 10646
                filteredBytes[filteredLength++] = c;
            }
        }
```

- the real services names:

1 | 1 | 47 | 東森購物1台 | 1 | digital television service |   | 1 | 1 | 4 | 0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 49 | 壹電視新聞台 | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 50 | 年代新聞台 | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 51 | 東森新聞台 | 1 | digital television service |   | 1 | 1 | 4 | 0
1 | 1 | 76 | WakuWaku Japan | 1 | digital television service |   | 1 | 1 | 4 | 0

**Comment by EricBerendsen** [comment]
Thank you for the test stream.

I decided to go for a bit different solution, do the charset decoding first and then filer out control codes 0x80-0x9f. (Also UTF-8 can have embedded control codes). That is pushed to master.

Now there is still a problem with the service names in the mouse over in the EITView:
![image](https://user-images.githubusercontent.com/50879515/104368607-97410c80-551c-11eb-9910-f2d5b9988993.png)

To fix that String getEscapedHTML(..) in Utils.java has to be rewritten, to also do charset decoding before interpreting control codes. Don't have time for that today, some time this week...

**Comment by EricBerendsen** [comment]
Fixed service name in mouse over in EIT view (and improved some other parts of HTML view of Event)

![image](https://user-images.githubusercontent.com/50879515/104783956-7af4d800-5787-11eb-9197-0dd40e067f94.png)

Should be fixed now.
