### ISSUE TITLE
SCTE-35 preroll timing

### ISSUE THREAD

**Issue by BartmanEH** [EricBerendsen/dvbinspector#14]
What I would really like to know is SCTE-35 splice event preroll timing: comparing the PTS of when the splice will execute against the PTS of when the command was issued. This is something only the Compressed Media Analyzer provides--no other analyzer I've tried has this feature. Maybe you can think of some way to implement it?
<img width="1596" alt="scte_info_channel_600_20210119" src="https://user-images.githubusercontent.com/6135879/106152208-2c621900-614b-11eb-8792-a20f7062eb1b.png">

**Comment by EricBerendsen** [comment]
I needed some time to investigate this one. 

There is a small problem, there is no PTS of when the command was issued. PTS's are only present in PESHeaders, and the SCTE-35 SpliceInfoSections are sent as SI tables, not elementary streams. Best thing we can do is take the packetnumber of the SpliceInfoSection (most of the time just one TS packet), and calculate the arrival time, in relation to the PCR of service.

You can get a visual indication of the ArmTime (or preroll) in the PCR/PTS/DTS graph. Splice_insert and Time Signal events are displayed there, and when you zoom in enough you can 'measure' the distance between command and PCR (see blue arrow);

![image](https://user-images.githubusercontent.com/50879515/106354682-e4322a80-62f3-11eb-9a6d-85435e6c3abb.png)

I can  also add an extra element to the treeview of splice_time , which basically calculates the difference between the current (calculated) pcr, and the pts_time specified in the splice_time element;

![image](https://user-images.githubusercontent.com/50879515/106354928-55261200-62f5-11eb-8a9f-102faf344be9.png)

Would this be what you are looking for?

**Comment by EricBerendsen** [comment]
Implemented preroll time on splice_time in [release 1.15](https://github.com/EricBerendsen/dvbinspector/releases/tag/release_1_15_0) Let me know if this works.

**Comment by BartmanEH** [comment]
> I needed some time to investigate this one.
> 
> There is a small problem, there is no PTS of when the command was issued. PTS's are only present in PESHeaders, and the SCTE-35 SpliceInfoSections are sent as SI tables, not elementary streams. Best thing we can do is take the packetnumber of the SpliceInfoSection (most of the time just one TS packet), and calculate the arrival time, in relation to the PCR of service.
Yes, I am aware that there is no timing info directly associated with SCTE-35 packets. That's why in my original query, I had asked if the timing could be correlated to the video service associated with the SCTE-35 command but missed specifying this in the new issue thread. You seem to have figured this out, of course, knowing much more about this than I.
> 
> You can get a visual indication of the ArmTime (or preroll) in the PCR/PTS/DTS graph. Splice_insert and Time Signal events are displayed there, and when you zoom in enough you can 'measure' the distance between command and PCR (see blue arrow);
I can't derive any precision out of this clutter :-(
> I can also add an extra element to the treeview of splice_time , which basically calculates the difference between the current (calculated) pcr, and the pts_time specified in the splice_time element; Would this be what you are looking for?
Yes! Exactly what I'm looking for, however, I'm getting a launch error with v1.15 although v1.14 launches just fine.

**Comment by EricBerendsen** [comment]
> Yes! Exactly what I'm looking for, however, I'm getting a launch error with v1.15 although v1.14 launches just fine.

Starting from this release java 11 is required (used to be java 8 until now). Check your version with java -version.

Also from your screenshot it looks like you are trying to start DVBinspector.jar. This is not the standalone jar, but should ve used in combination with the dvb.bat/sh scripts. Try running DVBinspector-1.15.0.jar

**Comment by BartmanEH** [comment]
Yes, I usually run `DVBinspector-1.15.0.jar` but the error message only appears once so I ran `DVBinspector.jar` to reproduce the error message. I will try to install Java 11.

**Comment by BartmanEH** [comment]
Ugh, I'm hopeless at this Java environment stuff. Just installed Java JDK 15 and 11 but still won't launch:
`java -version
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)`

**Comment by BartmanEH** [comment]
> Implemented preroll time on splice_time in [release 1.15](https://github.com/EricBerendsen/dvbinspector/releases/tag/release_1_15_0) Let me know if this works.
I tested v1.15 and it does report exactly what I'm looking for for Preroll. The "other analyzer" reports 5.809s whereas yours reports 5.810s.

**Comment by BartmanEH** [comment]
thank you for implement preroll timing indicator for SCTE-35!

**Comment by BartmanEH** [comment]
Loving this. Just wanted to thank you again for adding preroll timing.

**Comment by BartmanEH** [comment]
> Best thing we can do is take the packetnumber of the SpliceInfoSection (most of the time just one TS packet), and calculate the arrival time, in relation to the PCR of service. [...and] add an extra element to the treeview of splice_time , which basically calculates the difference between the current (calculated) pcr, and the pts_time specified in the splice_time element;
Can you explain how the `current (calculated) pcr` is derived? Do you find the last PTS and add to that the timing of the number of packets between that PTS and the SpiceInfoSection using the bitrate? This would vary based on the number of bytes per packet so how is that accounted for? Do you sum all the bytes in all the packets between the PTS packet byte and the SpliceInfoSection packet?
