### ISSUE TITLE
[Suggestion] search and export function for EPG data

### ISSUE THREAD

**Issue by JanOonk** [EricBerendsen/dvbinspector#15]
Thanks for this great tool.

In the EIT View you can see the EPG/TV guide data where you can also export it to .png.
Would be great if you can also export this data to json/xml/txt.

Furthermore some search function would be great. For example search for a certain program, description, actor or whatever.

**Comment by EricBerendsen** [comment]
Problem with exporting "the EIT" as text/csv/xml is that there is very little fixed structure to events. The only thing all events have is a duration and free_CA_mode field. Even start_time can be missing when it is about NVOD events (these events are also not shown in the current view) ShortEventDescriptors with event_name may be present, missing, or even multiple (multiple languages).  This makes a fixed format like csv difficult. 

XML/json could be more flexible, still lot of questions. How would you handle multiple extended_event_descriptors? Should the text of these be concatenated into a single field, or a field for each extended_event_descriptor? First option is how decoders present it. (and how it is now displayed in the mouse over). etc.

So not very straight forward. Now I kind of have a work around with the mouse-over (in EITView) or htmlView (in treeview) where any available descriptors can be displayed in a hopefully sensible order;

![image](https://user-images.githubusercontent.com/50879515/107156541-307a0c00-697f-11eb-838d-668c52ff4655.png)

I am open for suggestions for an export function.

Regarding searching; the treeview has a very basic search function. If your search string is unique enough it should be quite easy to find the relevant event(s).

**Comment by JanOonk** [comment]
I meant an export function for the EPG data shown in yellow mouse over tooltips when in EIT View tab. Just dump that info in a json like format. 
I am already very happy with the info shown already in the tooltips.
Loop over all channels and make an object per event. For all info available for the Event use a key-value pair.
[
  {
    "Event name": "Bring It On",
    "Year": 2000,
    "Channel": "SBS9",
    "Start": "2021-02-06T20:30:00+01:00",
    "Duration" : "...",
    "episode-num": "...",
    "Rating": "...",
   "Minimum age": "..",
    "Content type": "....",
 "Actors" : [ "Actor1","Actor2","Actor3"]
  },
....
]

When there are multiple key's like actor, director, producer you could use an array for the values.

That way I can more easily search or do additional processing on the EPG data. The current search function is pretty basic and my search strings are not unique.

I cloned the project and but noticed you used Swing which I am not really familiar with, only JavaFX. Also it's quite a big project... if you could give me some pointers where to look for I can try to implement it.

**Comment by EricBerendsen** [comment]
I think it is a bit more complicated. Your JSON example looks simple, but there are a lot of details to take into account

There may be multiple channels with the same name in the EIT. In the JSON these would have the same name.
There are no separate fields for actor, producer, etc. There may be items in the extended_event_descriptor, but they can contain any "fieldname", in any language. Also episode-num, rating, is not present in a structured way (it may be there as free text). i don not see a simple, robust and elegant solution for exporting the EIT as (structured) text, in whatever form

I don't know what you are trying to achieve, but I doubt DVB Inspector is the right tool for that.  With DVB Inspector I try to visualize the structure of the data, whether it is video, audio, teletext or EIT information. When it possible to display the actual data that is nice to have, but not essential.

**Comment by JanOonk** [comment]
I guess you have a point. I (just) want to extract the EPG data as text (structured or unstructured) so I can search, filter on it more easily or do some other processing on it. Do such tools exist?
Well until I have a better EPG extract tool I will use yours... I like it thanks.

**Comment by EricBerendsen** [comment]
Good to see you found a solution to your problem. From your link; EPGCollector has the same problem, there is no standard for tags like episode, rating, etc.  So EPGCollector is doing some ad hoc parsing, but as that is very much depending on language and provider I still think it is not a good approach for DVB Inspector.
