### ISSUE TITLE
Exception java.lang.IllegalArgumentException: new child is null

### ISSUE THREAD

**Issue by jan-adam** [EricBerendsen/dvbinspector#20]
Hello,

I have been using DVB Inspector for many years to inspect DVB-T transport streams in Poland. Right now, on the eve of the migration to DVB-T2, broadcasters are launching new transmitters.

Unfortunately, one of the new multiplexes is causing an exception in DVB Inspector. The full error message is

_Ooops.
While displaying your stream an error occurred from which DVB Inspector can not recover.
java.lang.IllegalArgumentException: new child is null_

Transport stream seems OK. It plays properly in VLC and Windows Movies & TV app. Moreover, MediaInfo app displays correct information about its content. The "problematic" transport stream is here for download (one program and full multiplex, none of them work in DVB Inspector):

https://www.dropbox.com/sh/t9vp81l3pya9020/AACcAC8jFqZfTpOfHU6S1V-Da?dl=0

I hope this helps to fix this issue.
Best regards.

**Comment by EricBerendsen** [comment]
Thanks  for reporting this. There is an issue in the frequency_list_descriptor in the NIT. It has coding_type 0, which is is not defined in EN 300 468 V1.16.1. When trying to display the centre_frequency in a formatted way DVB inspector depends on the coding_type, and 0 caused a problem. Now fixed, for 0 it does not try to format the value, and also small adjustments for other types.

This is fixed view for coding_type==0;
![image](https://user-images.githubusercontent.com/50879515/115076082-5b8f5780-9efc-11eb-9eae-0fc50ce1a30a.png)

and this is what formatted view looks like for a valid DVB-T2 stream from NL;
![image](https://user-images.githubusercontent.com/50879515/115076320-b0cb6900-9efc-11eb-83ce-225cfd1bd687.png)

Would be interesting to see what the other new multiplexes have as value.

You can find a snapshot build at the bottom of this page, under artifacts, snapshot; [https://github.com/EricBerendsen/dvbinspector/actions/runs/756702133](https://github.com/EricBerendsen/dvbinspector/actions/runs/756702133)

**Comment by jan-adam** [comment]
Thank you for the quick reply!

I inspected all multiplexes, results below.

* 4 nationwide DVB-T muxes have coding_type: 0x3
* 1 local/private DVB-T mux has no frequency_list_descriptor
* 1 nationwide DVB-T2 mux (discussed in this issue) has coding_type: 0x0
* 1 local/private DVB-T2 mux has no frequency_list_descriptor

According to plans, the migration to DVB-T2/HEVC will continue until June 2022.

Coming back to the issue, I wonder what the broadcaster would say. I will ask on his own internet forum, there should be an answer in a few days. Then we will also close this issue. 

Thanks again for the awesome software: DVB Inspector! :smile:

**Comment by jan-adam** [comment]
The coding_type has been changed to 0x3 in the transmitter configuration, so the broadcast is now compliant with EN 300 468 V1.16.1.
