### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Kitoko86** [EricBerendsen/dvbinspector#24]
Hi,

I tried to contact you via the form on your website but it always displays an error after submitting my comment.

**Comment by EricBerendsen** [comment]
Hi, sorry, have been having some issues with hosting the site. 

You can leave your comments in this thread, or if you want to keep it private mail to e_berendsen (at) digitalekabeltelevisie.nl

**Comment by Kitoko86** [comment]
Thanks a lot.

Sorry to open a issue ticket for this. I close it anyway.

Best Regards.

**Comment by Kitoko86** [comment]
Hi,

I sent you a mail but I'm not sure that you received it. It's about the sharing of .ts samples.

**Comment by Kitoko86** [comment]
Hi Eric,

Sorry to hijack this thread again but I sent you a mail about the update protocol for Ziggo STB. Did you receive it?

Best Regards.
