### ISSUE TITLE
BUG: Outdated dvb.bat and dvb.sh files

### ISSUE THREAD

**Issue by lars18th** [EricBerendsen/dvbinspector#26]
Hi @EricBerendsen ,

The new release has a bug for Windows and Linux users. The launch files `dvb.bat` and `dvb.sh` files are calling to outdated packages jars. Then it's impossible to launch the tool. Almost for Windows I use this to fix the error:
```
"C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -classpath .;.\lib\jfreechart-1.5.3.jar;.\lib\opencsv-5.5.2.jar;.\lib\jlayer-1.0.1.4.jar;.\lib\commons-text-1.9.jar;.\lib\commons-logging-1.2.jar;.\lib\commons-lang3-3.12.0.jar;.\lib\commons-collections4-4.4.jar;.\lib\commons-collections-3.2.2.jar;.\lib\commons-beanutils-1.9.4.jar;.\DVBinspector.jar %JVM_FLAGS% -Djava.util.logging.config.file=src/main/resources/logging.properties nl.digitalekabeltelevisie.main.DVBinspector
```

I hope you'll update these files and indicate a method to link to the current version of the JRE. However, the most relevant action is to maintain the correct versions of the used packages.

Regards.

**Comment by EricBerendsen** [comment]
Hi @lars18th 

Thank you for reporting this. Will get a new version out ASAP.

About your second problem, having multiple JVMs installed and making sure to use the correct one; I am afraid there is no simple solution, apart from having just one JVM installed :-) In my experience if you installed the newest version last, that one will be used. 

 Java is moving in the direction of having each desktop application being packaged with its own JVM. That will mean different packages for different platforms, taking away one of the advantages of java.  Also it is now possible to crate native applications, again with the same drawback. Something I want to look into sometime.

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

Don't worry about the selected JRE. If you maintain the call to `java` it will be sufficient. In Windows, I only need to launch the "Configure Java" tool, and inside it configure **manually** the JRE. Each JDK requires to be added, and after activate only one. Using this from the CMD I can launch `java.exe -version` and check that is the correct one.

Thank you for your interest on fixing this.
Regards.
