### ISSUE TITLE
Wrong TSID in BAT

### ISSUE THREAD

**Issue by nextyazilim** [EricBerendsen/dvbinspector#31]
If TSID bigger than 4095 show wrong TSID in BAT.

DVBinspector-1.16.1
<html>
<body>

bouquet id | bouquet id name | bouquet name descriptor | tsid (WRONG) | tsid (CORRECT) | onid | original network name
-- | -- | -- | -- | -- | -- | --
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 1448 | 5600 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 4037 | 40901 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 2229 | 30901 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 3717 | 20101 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 2345 | 43305 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 1041 | 42001 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 1929 | 30601 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 3737 | 40601 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 441 | 41401 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 1042 | 42002 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 | Digital Platform BAT | 43 | 4103 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 3437 | 40301 |  42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 3937 | 40801 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 942 | 41902 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 1241 | 42201 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 7 | 7 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 3640 | 40504 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 743 | 41703 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 1729 | 30401 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 2830 | 31502 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 45 | 41005 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 2329 | 31001 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 1045 | 42005 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 3030 | 31702 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 61 | 61 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 941 | 41901 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 3 | 3 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 341 | 41301 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 1142 | 42102 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 1 | 1 | 42 | Päijät-Hämeen Puhelin Oyj
128 | Digital Platform DIGITURK1 |   | 541 | 41501 | 42 | Päijät-Hämeen Puhelin Oyj

</body>
</html>

[TS File](https://mega.nz/file/YE0QQTIA#3kbHeBjxeLs5y892SXw6nh2J7wvNiv6UJ-KMUZlPpF0)

**Comment by EricBerendsen** [comment]
Hi, thank you for reporting this. The problem was only 12 bits were used for the transport_stream_id, that should have been 16. Also the field original_network_id had the same problem.
