### ISSUE TITLE
Question: Any method to locate the continuity errors?

### ISSUE THREAD

**Issue by lars18th** [EricBerendsen/dvbinspector#32]
Hi,

In the PID list tree, I can see that the tool counts the "continuity errors" found in the stream. However, what do I have to do to go (locate) these packets? It will be desirable to have a method to go directly to these gaps.

Any idea?

**Comment by EricBerendsen** [comment]
Good question/suggestion. First would have to create a list of packetNo's. Maybe could just display that list (in the right panel when you select the item "continuity errors"?)

Jumping/navigating in the tree directly has some technical problems.

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

> Good question/suggestion. First would have to create a list of packetNo's. Maybe could just display that list (in the right panel when you select the item "continuity errors"?)

From my point of view, presenting a list of the packets will be a good solution. 👍 

> Jumping/navigating in the tree directly has some technical problems.

Ok. Don't worry! The usability will be sufficient if we can do the task.
Thank you.

**Comment by EricBerendsen** [comment]
This is what I came up with;

![image](https://user-images.githubusercontent.com/50879515/159158869-82bd3693-f394-4839-bc8c-6e9b6fff8faf.png)

Would that be useful?

**Comment by lars18th** [comment]
> Would that be useful?

Perfect! 👍

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

Is this already implemented? How to check it? I can close the issue?

**Comment by EricBerendsen** [comment]
Hi @lars18th 

Try a snapshot version at [https://www.digitalekabeltelevisie.nl/dvb_inspector/img/DVBinspector-1.17.0-SNAPSHOT-dist.zip](https://www.digitalekabeltelevisie.nl/dvb_inspector/img/DVBinspector-1.17.0-SNAPSHOT-dist.zip)

You will need Java 17!
