### ISSUE TITLE
Drag and drop support for re-opening

### ISSUE THREAD

**Issue by lars18th** [EricBerendsen/dvbinspector#52]
Hi,

When I want to use DVB Inspector I launch it from a ICON, and after I drag & drop the file to analyze. However, I have a frustration with this: when I want to analyze another different file, I need to close and open a new instance of the tool. That's because the drag & drop refuses to receive the file when another file is opened on it. So, could you please remove this restriction?

Thank you.

**Comment by EricBerendsen** [comment]
Hi,

It works fine on my machine :-) (Windows 10) What platform are you using? If it does not respond to drag and drop, can you still open a new file with the File Open menu?

Maybe you can try it started from the dvb.bat (or dvb.sh) file? That may log some more info in the console.

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

It seems that with the last RC this problem has gone. I'm using Windows 10 too, and the functionality now seems to work. Sorry to disturb you with a non-existent issue.

Regards.

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

I discovered the problem: I the RIGHT panel in the TREE window has the information of the content of the TS PACKET, then in this case, and only in this case, the Drag&Drop is refused.

Please check it!

**Comment by EricBerendsen** [comment]
You already provided a work around, just drop the file on the left panel!

The problem occurred with any formatted text (html) in the right panel. So also the new continuity errors view, and also the EIT schedule for a single channel;

![image](https://user-images.githubusercontent.com/50879515/202282808-2f5b471a-157d-4c49-b6ad-b72618e100a8.png)

Fixed it.

**Comment by lars18th** [comment]
Thank you.
