### ISSUE TITLE
SDT updates not reflected

### ISSUE THREAD

**Issue by lars18th** [EricBerendsen/dvbinspector#53]
Hi @EricBerendsen ,

I detected a very small (but not simple) bug:

- When you read a TS stream where it includes a change in the SDT table, you can see the "new" table and "old" table. In the PSI tree, you have the two. And you can see the two. Until here no problem.
- However, when you select the PSI/SDT or PSI/PAT main folder, what you're watching is the "old" version. For example, if a new service is added, then you don't see the NAME included in the new SDT table. You only can see (overall) the ID of the service.

Therefore I feel you need to update the data when a new version of the tables appears. And the issue is complex to fix it because it's not sufficient to use the las table. For example, perhaps a service is removed (not added). So in this case you need to "merge" more or less the new with the old data.

Perhaps you never have seen this. But it can appear and I want to report it.
Regards.

**Comment by EricBerendsen** [comment]
Hi @lars18th 

I understand the issue. Must admit I did not test the table views with multiple versions of PAT/SDT, etc. 

At the moment the tables show the view of the first (oldest) version of the data. That is a consistent view of the data at that moment. Showing a "merged" version would show something that never occurred. Then you would have to somehow mark rows as deleted or new. (I did something like that [here](https://www.digitalekabeltelevisie.nl/techniek/tvhome.shtml). It was not easy.)

It would be even more complicated for all the possible changes for all types of tables.

Still it is worth playing around with. Do you have some test streams available?

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

> Still it is worth playing around with. Do you have some test streams available?

My test streams are synthetic streams manipulated with the TSDuck toolkit. However, if you need one then I can prepare one to share with you.

> It would be even more complicated for all the possible changes for all types of tables.

Yes, I feel it's not necessary to complicate a lot the code for a small advantage. However, in order to handle such cases I have one simple proposal:
- When more than one version of a PSI table is found, then the user will have the option to _global_ use one or another. With the right mouse button it could select an specific version of the table from the PSI tree when it has selected.

With this support you can use by default the older version (as now). But the user can then enforce to use the never version. And then all parts of the tool will use the information selected. This will include the names of the services, for example if the SDT table is updated. But will be also true for any other PSI table. I feel this is sufficient easy to implement it, and at the same time sufficient powerful.
What you think?

**Comment by lars18th** [comment]
Ok. Thank you for the answer.
