### ISSUE TITLE
dvb.sh uses dos style newlines

### ISSUE THREAD

**Issue by tmm1** [EricBerendsen/dvbinspector#56]
I get this error on macos unless I run `dos2unix` first:

>dvb.sh: bad interpreter: /bin/bash^M: no such file or directory

**Comment by EricBerendsen** [comment]
Hi, Thanks a lot for reporting this. 

That is what you get from trying to create linux files on windows...
Fixed now, and verified on a raspberry PI.

**Comment by tmm1** [comment]
Appreciate it! Thanks for a great piece of software.
