### ISSUE TITLE
transport_protocol_descriptor url_extension_byte off by one

### ISSUE THREAD

**Issue by sofia-tsa** [EricBerendsen/dvbinspector#6]
Transport protocol descriptor lists url_extension_byte values incorrectly. If the extension is for example "foobar" the UI shows it as ".fooba". The reason is that the length of the extension field is included in the extension bytes and the final byte of the extension is dropped. I have attached a diff that seems to fix the issue.

[transport_protocol_descriptor_diff.txt](https://github.com/EricBerendsen/dvbinspector/files/5347664/transport_protocol_descriptor_diff.txt)

**Comment by EricBerendsen** [comment]
Thank you very much for reporting and for the patch. I don't have any test data where the url_extension_byte is used, so this bug is the result of programming "in the blind". Then a mistake is easily made.
