### ISSUE TITLE
White highlight of table in Private Data in Dark Mode on Ubuntu makes text unreadable 

### ISSUE THREAD

**Issue by tomyummmm** [EricBerendsen/dvbinspector#63]
Hi, as mentioned above, on Ubuntu 22.04 with Dark mode enabled in settings, the white highlight of table in Private Data in Dark Mode on Ubuntu makes text unreadable. Until I select all in the table, which changes it to highlight orange, and white text.

![Screenshot from 2023-07-31 09-39-48](https://github.com/EricBerendsen/dvbinspector/assets/65211592/18477e0d-f729-4515-8132-0ca739facae4)

**Comment by EricBerendsen** [comment]
Welcome to java; write once, debug everywhere :-)  I tried light and dark mode on Windows and Raspberry Pi, but DVB Inspector just ignores that and always displays the same.  Maybe it depends on which java is used?

There is no standard support in java to detect the dark/light mode used on that machine. And I think it goes a bit too far to make the DVB Inspector GUI configurable for that. So best solution is probably just to set the foreground colour to black.

**Comment by tomyummmm** [comment]
Hi, I built and tested, it indeed fixed the issue, text is now black colour on white highlight, which is readable. Thanks!
