### ISSUE TITLE
Question: Muxing delay calculation

### ISSUE THREAD

**Issue by lars18th** [EricBerendsen/dvbinspector#69]
Hi @EricBerendsen ,

To check the correctness of a muxer, it would be interesting to have this information: the delay between the time stamps of the PES data and the PCR time clock. Therefore, here is my suggestion:
- When parsing the PES data, for each packet, in the `pts` field the tool adds the time difference between this timestamp and the PUSI packet (the start of the PES packet) in reference to the PCR time clock (calculating the clock until the first TS packet of the PES stream).

Here one example:
```
Video 14496 PES Packet
+-Start TS Packet No: 0x242 (578)
+-stream_id: 0xE0 (224) => ITU-T Rec. H.262 | ISO/IEC 13818-2 or ISO/IEC 11172-2 or ISO/IEC 14496-2 video stream number 0
+-PES_packet_length: 0x8B7 (2231)
+ ...
+-pts: 0xE15D4 (923092) => 0:00:10.2565  (PCR time difference: 0:00:00.0123)
```

The problem is that some tools (like the FFmpeg encoder) when muxing MPEG-TS streams, are not very good when muxing multiple services with VBR video streams in a CBR transport stream. And the idea is to have a tool that checks these differencies.

What you think?

**Comment by lars18th** [comment]
No comments?

**Comment by EricBerendsen** [comment]
Hi @lars18th ,

Sorry, this one slipped through. 

I think the PCR/PTS/DTS graph would be more helpful for this kind of information. You can see in a single glance which packets are high above the PCR line, so they arrived very early. Sure, you can not see the exact values, but it is easier to see strange patterns (or values below the PCR line, which means they arrived to late). Do you really need exact values?

![image](https://github.com/user-attachments/assets/1ff50a25-741d-4447-8dc0-f100a3d1629b)

When including this in the Tree view for each packet, you would have to de a lot of clicking to see all packets.

**Comment by lars18th** [comment]
Hi @EricBerendsen ,

I think you're right. Thanks for the answer. Anyway, a suggestion: could you add keyboard scrolling on the Graph? The idea is to zoom with the mouse, and then use the <LEFT>,<UP>,<DOWN>,<RIGHT> keys to move the pan. Do you agree?

**Comment by EricBerendsen** [comment]
> 
>  Anyway, a suggestion: could you add keyboard scrolling on the Graph? The idea is to zoom with the mouse, and then use the LEFT,UP,DOWN,RIGHT keys to move the pan. Do you agree?

This graph is implemented using a library (JFreeChart), and its behaviour is mostly fixed. To scroll using the mouse press CTRL while dragging the mouse.
