### ISSUE TITLE
Moving to Java 11

### ISSUE THREAD

**Issue by EricBerendsen** [EricBerendsen/dvbinspector#8]
DVB Inspector will be migrating to Java 11.  From now on all code should be compiled with Java 11, and from the next release (1.15) a Java 11 JRE will be needed to run DVB Inspector.

One of my goals with developing DVB Inspector is learning new Java features. So I am trying to find a balance between using the latest Java version, and not forcing users to migrate too often. Java 11 has been available for two years now, and is an Oracle Long-Term-Support (LTS) release.

**Comment by BartmanEH** [comment]
but Java 11 is not well integrated for Macos. Java 8 had a full installer from Oracle that included a Java preferences pane in Settings and java launcher app that enabled double-clicking .jar files to launch them. None of this works with Java 11--here is [an example of the issue](https://github.com/AdoptOpenJDK/openjdk-installer/issues/93).
I am getting around the issue by creating my own Macos app that launches:
`java -jar [pathto]\DVBinspector-1.15.0.jar`

**Comment by EricBerendsen** [comment]
Sorry about your issues, but that is java for you; write once, debug everywhere...  Thanks for the tips, maybe it will help some other Mac users.

I try not to upgrade the java version too often, because I know it can cause issues for some users. On the other hand, one of the reasons for me to do this project is to learn and play around with new java features. 

Java 11 has been out for over 2 years now, so I think it is reasonable to migrate to 11.

**Comment by barbudor** [comment]
Hi Eric, following up our email exchange
As I'm not a Java developper I don't understand what is Java 11. The only version I see for download on Java.com is 1.8.0_281.
Only reference I see to a Java 11 is a SDK which doesn't make sense to the user I am (not a Java dev).
Could you please kindly advise what is necessary to do ?
Thanks

**Comment by EricBerendsen** [comment]
I am a bit surprised that java.com is only showing 1.8,  (also know as java 8). But you can find different versions on [https://www.oracle.com/java/technologies/javase-downloads.html](https://www.oracle.com/java/technologies/javase-downloads.html) . Just download the SDK (it includes a JRE) , There is no longer a separate JRE available.

 I would advise to select Java SE 11 (LTS), the LTS being the long term support version. If you prefer, or the license of Oracle does not fit your use, you can select java 11 from [https://adoptopenjdk.net/](https://adoptopenjdk.net/)

**Comment by BartmanEH** [comment]
I have made a better work around for Java 11 on macOS: use Automator to create your own java launcher app:
<img width="977" alt="Screen Shot 2021-02-04 at 4 14 57 PM" src="https://user-images.githubusercontent.com/6135879/106956220-4f209e80-6704-11eb-90fc-110067bb3b92.png">
Select a .jar file in Finder and Get Info. Under the Open With section, find your java launcher app created with Automator, use the `Select All...` button to associate all .jar files with your java launcher app. In this way I can now double click a Java 11 .jar file in Finder and it will launch.
